# Generated by Django 4.1 on 2022-09-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="items/")),
                ("brand", models.CharField(max_length=150)),
                ("item", models.TextField()),
                ("mrp", models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, max_digits=7, null=True),
                ),
                ("status", models.BooleanField()),
                ("product_details", models.TextField(null=True)),
                ("style_note", models.TextField(null=True)),
                ("date_created", models.DateField(auto_now_add=True)),
                ("slug", models.TextField(null=True)),
            ],
            options={"ordering": ["-date_created"],},
        ),
    ]
