# Generated by Django 4.1.2 on 2022-10-18 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categories",
                    models.CharField(
                        choices=[
                            ("S", "Shirt"),
                            ("WW", "Winter Wear"),
                            ("TP", "Top wear"),
                            ("BP", "Bottom wear"),
                            ("FW", "Foot wear"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="mult_img",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=50, null=True)),
                ("image1", models.ImageField(blank=True, upload_to="items/")),
                ("image2", models.ImageField(blank=True, upload_to="items/")),
                ("image3", models.ImageField(blank=True, upload_to="items/")),
                ("image4", models.ImageField(blank=True, upload_to="items/")),
                ("image5", models.ImageField(blank=True, upload_to="items/")),
            ],
        ),
        migrations.RenameField(
            model_name="product",
            old_name="item",
            new_name="item_name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="discount",
            new_name="original_mrp",
        ),
        migrations.RemoveField(
            model_name="product",
            name="mrp",
        ),
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="product",
            name="style_note",
        ),
        migrations.AddField(
            model_name="product",
            name="discounted_percent",
            field=models.DecimalField(
                decimal_places=2, max_digits=7, null=True, verbose_name="discount  %"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.category",
            ),
        ),
    ]
