# Generated by Django 4.1 on 2022-09-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact_us",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="itemcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="items/")),
                ("brand", models.CharField(max_length=150)),
                ("mrp", models.DecimalField(decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="product", old_name="discount", new_name="discount_Percentage",
        ),
        migrations.RemoveField(model_name="product", name="style_note",),
        migrations.AddField(
            model_name="product", name="rating", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
