# Generated by Django 4.1 on 2022-09-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_product_image_product_icon"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="icon",),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="items/"),
        ),
    ]
