# Generated by Django 4.1.2 on 2022-10-18 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_mult_img_rename_discount_product_discounted_mrp_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="discounted_mrp",
            new_name="discounted_percent",
        ),
    ]
