# Generated by Django 4.1 on 2022-10-13 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_contact_us_itemcard_pics_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="pics",
            new_name="mult_img",
        ),
    ]
