# Generated by Django 4.1 on 2022-09-22 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_contact_us_itemcard_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(5),
                    django.core.validators.MinLengthValidator(5),
                ],
            ),
        ),
    ]
