# Generated by Django 4.1 on 2022-09-17 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_react"),
    ]

    operations = [
        migrations.DeleteModel(name="React",),
    ]
