# Generated by Django 4.1 on 2022-09-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_product_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="rating", field=models.IntegerField(null=True),
        ),
    ]
