# Generated by Django 4.1.2 on 2022-10-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="categories",
            new_name="category",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("S", "Shirt"),
                    ("WW", "Winter Wear"),
                    ("TP", "Top wear"),
                    ("BP", "Bottom wear"),
                    ("FW", "Foot wear"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
