# Generated by Django 4.1 on 2022-09-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_delete_react"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="image", field=models.URLField(max_length=300),
        ),
    ]
