# Generated by Django 4.1 on 2022-10-14 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_pics_mult_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photo",
                to="core.mult_img",
            ),
        ),
    ]
