# Generated by Django 4.1 on 2022-09-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_product_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact_us",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
