# Generated by Django 4.1.2 on 2022-10-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemcard",
            old_name="discount_Percentage",
            new_name="discounted_mrp",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="discount_Percentage",
            new_name="discounted_mrp",
        ),
    ]
