# Generated by Django 4.1.2 on 2022-10-16 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_discount_percentage_itemcard_discounted_mrp_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemcard",
            old_name="mrp",
            new_name="original_mrp",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="mrp",
            new_name="original_mrp",
        ),
    ]
