# Generated by Django 4.1.2 on 2022-10-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_product_discounted_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discounted_percent",
            field=models.DecimalField(
                decimal_places=2, max_digits=7, null=True, verbose_name="discount  %"
            ),
        ),
    ]
