# Generated by Django 4.1.2 on 2022-10-18 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_mult_img_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mult_img",
            name="brand",
        ),
    ]
