# Generated by Django 4.1.2 on 2022-10-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_product_category_category_prdt"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Category",
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
