# Generated by Django 4.1.2 on 2022-10-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="Category",
        ),
    ]
