# Generated by Django 4.1.2 on 2022-10-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="prdt",
            field=models.IntegerField(null=True),
        ),
    ]
