# Generated by Django 4.1.2 on 2022-10-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_auto_20221019_0009"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="prdt",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("S", "Shirt"),
                    ("WW", "Winter Wear"),
                    ("TP", "Top wear"),
                    ("BP", "Bottom wear"),
                    ("FW", "Foot wear"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="mult_img",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
