# Generated by Django 4.1.2 on 2022-10-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_product_prdt_product_category_product_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categories",
                    models.CharField(
                        choices=[
                            ("S", "Shirt"),
                            ("WW", "Winter Wear"),
                            ("TP", "Top wear"),
                            ("BP", "Bottom wear"),
                            ("FW", "Foot wear"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
