# Generated by Django 4.1.2 on 2022-10-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_product_category_category_prdt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="prdt",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("WW", "Winter Wear"),
                    ("SW", "Summer Wear"),
                    ("TW", "Top wear"),
                    ("BW", "Bottom Wear"),
                    ("FW", "Foot wear"),
                    ("N", "Null"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
