# Generated by Django 4.1.2 on 2022-10-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_rename_quantity_product_stock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="original_mrp",
            field=models.IntegerField(null=True),
        ),
    ]
